// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BalanceInfo struct {
	Name     string `json:"name"`
	Symbol   string `json:"symbol"`
	Amount   string `json:"amount"`
	Decimals int    `json:"decimals"`
	Address  string `json:"address,omitempty"`
}

type BlockInfo struct {
	Number           uint64 `json:"number"`
	Hash             string `json:"hash"`
	ParentHash       string `json:"parentHash"`
	Time             uint64 `json:"time"`
	Confirmations    uint64 `json:"confirmations"`
	GasLimit         uint64 `json:"gasLimit"`
	GasUsed          uint64 `json:"gasUsed"`
	BaseFee          uint64 `json:"baseFee"`
	TransactionCount int    `json:"transactionCount"`
}

type EventLog struct {
	TxHash      string         `json:"tx_hash"`      // 交易hash，0x开头，方便转换
	Address     string         `json:"address"`      // 合约地址
	EventName   string         `json:"event_name"`   // 事件名称
	BlockNumber int64          `json:"block_number"` // 区块号
	LogIndex    int64          `json:"log_index"`    // 日志索引
	Topics      []EventLogData `json:"topics"`       // 索引字段
	Data        []EventLogData `json:"data"`         // 非索引字段
	TxTimestamp string         `json:"tx_timestamp"` // 交易时间
}

type EventLogData struct {
	Index int    `json:"index"`
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type GetBalanceReq struct {
	Address      string `form:"address"`
	TokenAddress string `form:"tokenAddress,optional"`
}

type GetBlockInfoReq struct {
	Number int64  `form:"number,optional"`
	Hash   string `form:"hash,optional"`
	Tag    string `form:"tag,optional"`
	Start  int64  `form:"start,optional"`
	End    int64  `form:"end,optional"`
}

type GetTransactionInfoReq struct {
	Hash string `path:"hash"`
}

type GetTransactionsReq struct {
	Address   string `form:"address"`
	PageIndex int    `form:"pageIndex"`
	PageSize  int    `form:"pageSize"`
}

type ListResponse struct {
	PageSize   int64       `json:"pageSize"`
	PageIndex  int64       `json:"pageIndex"`
	TotalCount int64       `json:"totalCount"`
	List       interface{} `json:"list"`
}

type PullTransactionsReq struct {
	StartBlock uint64 `form:"startBlock"`
	EndBlock   uint64 `form:"endBlock"`
}

type QueryEventLogReq struct {
	Address   string `form:"address,optional"`
	TxHash    string `form:"txHash,optional"`
	PageIndex int    `form:"pageIndex"`
	PageSize  int    `form:"pageSize"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type TokenBalances struct {
	EthBalance    *BalanceInfo   `json:"ethBalance"`
	TokenBalances []*BalanceInfo `json:"tokenBalances"`
}

type Transaction struct {
	Hash      string `json:"hash"`
	From      string `json:"from"`
	To        string `json:"to"`
	Value     uint64 `json:"value"`
	DataLen   int    `json:"dataLen"`
	Gas       uint64 `json:"gas"`
	GasPrice  uint64 `json:"gasPrice"`
	Nonce     uint64 `json:"nonce"`
	IsPending bool   `json:"isPending"`
	Timestamp uint64 `json:"timestamp"`
	TransactionReceipt
}

type TransactionReceipt struct {
	Status      uint64 `json:"status,omitempty"`
	BlockNumber uint64 `json:"blockNumber,omitempty"`
	BlockHash   string `json:"blockHash,omitempty"`
	TxIndex     uint64 `json:"txIndex,omitempty"`
	Logs        uint64 `json:"logs,omitempty"`
	GasUsed     uint64 `json:"gasUsed,omitempty"`
}
