// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	v1balance "github.com/KyoUK4n/etherscan/internal/handler/v1/balance"
	v1blocks "github.com/KyoUK4n/etherscan/internal/handler/v1/blocks"
	v1transaction "github.com/KyoUK4n/etherscan/internal/handler/v1/transaction"
	"github.com/KyoUK4n/etherscan/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/balances",
				Handler: v1balance.GetBalanceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/blocks",
				Handler: v1blocks.GetBlocksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blocks/info",
				Handler: v1blocks.GetBlockInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/transactions",
				Handler: v1transaction.GetTransactionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/transactions/:hash",
				Handler: v1transaction.GetTransactionInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/transactions/events",
				Handler: v1transaction.QueryEventLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/transactions/pull",
				Handler: v1transaction.PullFromBlockHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
