// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	eventLogFieldNames          = builder.RawFieldNames(&EventLog{})
	eventLogRows                = strings.Join(eventLogFieldNames, ",")
	eventLogRowsExpectAutoSet   = strings.Join(stringx.Remove(eventLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	eventLogRowsWithPlaceHolder = strings.Join(stringx.Remove(eventLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	eventLogModel interface {
		Insert(ctx context.Context, data *EventLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EventLog, error)
		Update(ctx context.Context, data *EventLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEventLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EventLog struct {
		Id          int64          `db:"id"`           // 自增主键
		TxHash      string         `db:"tx_hash"`      // 交易hash，0x开头，方便转换
		Address     string         `db:"address"`      // 合约地址
		EventName   string         `db:"event_name"`   // 事件名称
		BlockNumber int64          `db:"block_number"` // 区块号
		LogIndex    int64          `db:"log_index"`    // 日志索引
		Topics      sql.NullString `db:"topics"`       // 索引字段
		Data        sql.NullString `db:"data"`         // 非索引字段
		TxTimestamp time.Time      `db:"tx_timestamp"` // 交易时间
	}
)

func newEventLogModel(conn sqlx.SqlConn) *defaultEventLogModel {
	return &defaultEventLogModel{
		conn:  conn,
		table: "`event_log`",
	}
}

func (m *defaultEventLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEventLogModel) FindOne(ctx context.Context, id int64) (*EventLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", eventLogRows, m.table)
	var resp EventLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEventLogModel) Insert(ctx context.Context, data *EventLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, eventLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TxHash, data.Address, data.EventName, data.BlockNumber, data.LogIndex, data.Topics, data.Data, data.TxTimestamp)
	return ret, err
}

func (m *defaultEventLogModel) Update(ctx context.Context, data *EventLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, eventLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TxHash, data.Address, data.EventName, data.BlockNumber, data.LogIndex, data.Topics, data.Data, data.TxTimestamp, data.Id)
	return err
}

func (m *defaultEventLogModel) tableName() string {
	return m.table
}
