// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionFieldNames          = builder.RawFieldNames(&Transaction{})
	transactionRows                = strings.Join(transactionFieldNames, ",")
	transactionRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	transactionRowsWithPlaceHolder = strings.Join(stringx.Remove(transactionFieldNames, "`tx_hash`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	transactionModel interface {
		Insert(ctx context.Context, data *Transaction) (sql.Result, error)
		FindOne(ctx context.Context, txHash string) (*Transaction, error)
		Update(ctx context.Context, data *Transaction) error
		Delete(ctx context.Context, txHash string) error
	}

	defaultTransactionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Transaction struct {
		TxHash      string       `db:"tx_hash"` // 交易hash
		TxIndex     int64        `db:"tx_index"`
		From        string       `db:"from"`  // 发送者
		To          string       `db:"to"`    // 接收者
		Value       string       `db:"value"` // 发送的eth(Wei),用varchar防止bigint溢出
		GasLimit    int64        `db:"gas_limit"`
		GasPrice    int64        `db:"gas_price"`
		GasUsed     int64        `db:"gas_used"`
		Nonce       int64        `db:"nonce"`
		Status      int64        `db:"status"`
		BlockNumber int64        `db:"block_number"`
		BlockHash   string       `db:"block_hash"`
		TxTimestamp sql.NullTime `db:"tx_timestamp"`
	}
)

func newTransactionModel(conn sqlx.SqlConn) *defaultTransactionModel {
	return &defaultTransactionModel{
		conn:  conn,
		table: "`transaction`",
	}
}

func (m *defaultTransactionModel) Delete(ctx context.Context, txHash string) error {
	query := fmt.Sprintf("delete from %s where `tx_hash` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, txHash)
	return err
}

func (m *defaultTransactionModel) FindOne(ctx context.Context, txHash string) (*Transaction, error) {
	query := fmt.Sprintf("select %s from %s where `tx_hash` = ? limit 1", transactionRows, m.table)
	var resp Transaction
	err := m.conn.QueryRowCtx(ctx, &resp, query, txHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionModel) Insert(ctx context.Context, data *Transaction) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, transactionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TxHash, data.TxIndex, data.From, data.To, data.Value, data.GasLimit, data.GasPrice, data.GasUsed, data.Nonce, data.Status, data.BlockNumber, data.BlockHash, data.TxTimestamp)
	return ret, err
}

func (m *defaultTransactionModel) Update(ctx context.Context, data *Transaction) error {
	query := fmt.Sprintf("update %s set %s where `tx_hash` = ?", m.table, transactionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TxIndex, data.From, data.To, data.Value, data.GasLimit, data.GasPrice, data.GasUsed, data.Nonce, data.Status, data.BlockNumber, data.BlockHash, data.TxTimestamp, data.TxHash)
	return err
}

func (m *defaultTransactionModel) tableName() string {
	return m.table
}
